### ISSUE TITLE
Landing page and icon and the default ones from Vite not OSCAR.

### ISSUE THREAD

**Issue by micafer** [grycap/oscar-dashboard#1]
https://github.com/grycap/oscar-dashboard/blob/8720fa184b0ff8565c8d0fbcff57cc25b4a4341e/index.html#L5-L7

**Comment by prosfus** [comment]
Ahora se utiliza el favicon de OSCAR y además el titulo de "Vite + React + TS" se ha reemplazado por OSCAR - {apartado} (por ejemplo OSCAR - Services)
